FROM diku-hcc/base:latest
MAINTAINER Martin Gruenbaum "martin@itsolveonline.net"

RUN mkdir /opt/torch
ADD ./src/torch /opt/torch
ADD ./docker-scripts/torch /opt/torch/scripts
WORKDIR /opt/torch

CMD "th"
