FROM diku-hcc/base:latest
MAINTAINER Martin Gruenbaum "martin@itsolveonline.net"

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# Lua dependencies
RUN luarocks install https://raw.githubusercontent.com/benglard/htmlua/master/htmlua-scm-1.rockspec && \
    luarocks install https://raw.githubusercontent.com/benglard/waffle/master/waffle-scm-1.rockspec

RUN mkdir /opt/server
ADD ../lua-src /opt/server

EXPOSE 8080
WORKDIR /opt/server
